### ISSUE TITLE
Feature: Add validation

### ISSUE THREAD

**Issue by JEQ7** [chungchunwang/Budibase-File-Upload#5] opened 2023-04-27 11:28 UTC
Hi I'm currently using the Budibase https://github.com/chungchunwang/Budibase-File-Upload plugin 

And I want to make this field **required** 

I try making the field column required in the database and then validate form 
But still I cant make the Budibase-File-Upload field required 

**(At less one file should be upload )**
Any suggestions??

**Comment by chungchunwang** [comment] 2023-04-28 16:38
Hi! Under the current implementation, an empty field would be considered as satisfying Budibase's "required" validation, as an empty JSON array is still stored in the field. However, you can circumvent this by adding another validation step that disallows the following string value:
``.[].`` - If you are using encoding protection
or 
``[]`` - If you are not using encoding protection

Also keep the required validation step as well - an empty array is not stored if the plugin is not clicked in the form.

**Comment by chungchunwang** [comment] 2023-04-28 16:41
Obviously, it would be better for the plugin to not store an empty array at all if there is not file stored; this would enable the required validation to work. I'm really busy as of the moment, but I will add this if I get the time.

**Comment by JEQ7** [comment] 2023-05-10 05:14
> Obviously, it would be better for the plugin to not store an empty array at all if there is not file stored; this would enable the required validation to work. I'm really busy as of the moment, but I will add this if I get the time.

That will be so **great and helpful** for us!!
We will wait for new release for the "**Budibase-File-Upload**" plugin

Thanks in advance @chungchunwang  :)

**Comment by chungchunwang** [comment] 2023-05-12 12:34
@JEQ7 Should be fixed! [Make sure to update the plugin in Budibase!](https://github.com/chungchunwang/Budibase-File-Upload/wiki/Updating-Budibase-Plugins)

**Comment by JEQ7** [comment] 2023-05-14 10:57
> @JEQ7 Should be fixed! [Make sure to update the plugin in Budibase!](https://github.com/chungchunwang/Budibase-File-Upload/wiki/Updating-Budibase-Plugins)


Dear @chungchunwang ,,
I have update the plugin but it still save with empty files!
See the attached video


Appreciate your support!


https://github.com/chungchunwang/Budibase-File-Upload/assets/81333578/56af3327-0210-4898-a15c-9680ef796ff3

**Comment by chungchunwang** [comment] 2023-05-14 13:28
Hi! Can I see what validation rule you have on the file upload field?

**Comment by chungchunwang** [comment] 2023-05-15 02:36
Oh, never mind, I see the problem. There is no validation field on the component at all. Will try to add this.

**Comment by JEQ7** [comment] 2023-05-15 03:24
Yes exactly it's only have an opinion for conditions to set

**Comment by chungchunwang** [comment] 2023-05-15 03:26
Hi @JEQ7! Ok, it should be fixed. Try updating again. There will now be a validation field on the object for you to set required on.

**Comment by JEQ7** [comment] 2023-05-15 05:30
Hi @chungchunwang 

It did work fine 
But I have problem with the error message can you delete that and let my write whatever I want?

It's seems that there is already default error message, **I want to be able to edit that!**

**if it will be editable will help me cause sometimes I will the to change the error message**

Kind regards appreciate your support!:)

See the attached pic

![image](https://github.com/chungchunwang/Budibase-File-Upload/assets/81333578/6d45012c-d39b-4f76-8320-f5fcea94874f)

![image](https://github.com/chungchunwang/Budibase-File-Upload/assets/81333578/5af630a8-0e6b-4242-94c8-2480a8026b68)

**Comment by chungchunwang** [comment] 2023-05-15 06:37
Hi! That is not an error message I set, maybe it could be caused by something else in your project? I do not get any popup messages at all on my end. Instead, the message shows up like this:
![image](https://github.com/chungchunwang/Budibase-File-Upload/assets/62127500/0efbc332-2775-4e43-a135-58996ca30309)
Currently the red error message only shows up if you upload a file and then delete it. I could not get it to update if the user attempts to submit the form.
Instead, submitting the form will quietly fail, meaning that the submission will not go through as long as the requirement is not satisfied. Besides the slight UI issue, this should solve your issue of not allowing empty fields. Maybe add a bit of text at the bottom of the form indicating to the user that the form won't submit if they don't upload a file.

**Comment by chungchunwang** [comment] 2023-05-15 06:39
By the way, sorry for the sudden influx of new version notifications - I am not at my normal computer and thus do not have the Budibase dev tool installed. Thus, I'm just publishing changes and then testing the compiled plugin.

**Comment by chungchunwang** [comment] 2023-05-15 06:58
I have asked for help here:
https://github.com/Budibase/budibase/discussions/10582
I'll update the plugin as soon as I figure out how to solve the issue.

**Comment by JEQ7** [comment] 2023-05-15 07:21
I have made it work correctly!
Thanks @chungchunwang  for your help and support :)

**Comment by chungchunwang** [comment] 2023-05-15 07:55
Great to hear!

**Comment by chungchunwang** [comment] 2023-05-18 00:31
> Currently the red error message only shows up if you upload a file and then delete it. I could not get it to update if the user attempts to submit the form.
> Instead, submitting the form will quietly fail, meaning that the submission will not go through as long as the requirement is not satisfied.

This should be fixed now! Turns out it was related to this default value issue #8.
![image](https://github.com/chungchunwang/Budibase-File-Upload/assets/62127500/a7816e5a-1cdd-41bc-a586-dfdc5ab119dd)

**Closed as completed by chungchunwang** 2023-05-18 00:31 UTC
Labels: enhancement
